### ISSUE TITLE
How to set lang other than english?

### ISSUE THREAD

**Issue by mahdi87gh** [ilich/NRecaptcha2#6]

**Comment by ilich** [comment]
It is not supported yet. I am going to research the topic and add this possibility.

**Comment by mahdi87gh** [comment]
Thanks 
your work is very handy and if it support this feature it'll be better.
please refer to these links
https://developers.google.com/recaptcha/docs/language

http://stackoverflow.com/questions/18859857/setting-recaptcha-in-a-different-language-other-than-english

**Comment by ilich** [comment]
I also found a discussion about reCAPTCHA 2. http://stackoverflow.com/questions/28769893/setting-recaptcha-verson-2-set-another-language-other-than-english

I hope I will be able to implement the fix soon.

**Comment by mahdi87gh** [comment]
It seems to be an easy fix.
Thanks man.
I appreciate your work.

**Comment by mahdi87gh** [comment]
Changing the link to API will fix it right away. no need to change any other thing

**Comment by ilich** [comment]
Yep. I will add a language property to make the API nicer. I think you can take the source code and reuse it in your project if you have to fix it quickly.

**Comment by mahdi87gh** [comment]
I just changed the API url and everything is fine. Thanks to you!

**Comment by ilich** [comment]
NRecaptcha2 v0.1.1 has been released
